### ISSUE TITLE
crear disseny bases de dades

### ISSUE THREAD

**Issue by Carlosgv11** [DanielPulidoSC/ColegasBorrachos#2]
.

**Comment by Carlosgv11** [comment]
quan tinguis feta l'estucutra entra al domini i crearla. amb 2-3 rows (no fa falta que siguin reals). Aixi també me la descarregaré jo i l'utilizaré per quan treballi desde casa meva.

**Comment by RandomSec12349** [comment]
He pujat el backup de la BD de PostgresSQL i les sentències de creació, neteja i inserció en txt
